      subroutine write_bondout(natoms, nbonds, ibond, jbond, btype)
c
c     Writes GICForge connectivity file "bondout"
c
c     INPUT:
c       natoms  - number of atoms
c       nbonds  - number of bonds
c       ibond   - first atom index of each bond
c       jbond   - second atom index of each bond
c       btype   - bond type code:
c                   1 = single
c                   2 = double
c                   3 = triple
c                   4 = aromatic
c
c     IMPORTANT:
c     Atom indices are 1-based, i.e. atom 1 corresponds to the
c     first atom listed in the XYZ file (Fortran-style indexing).
c
c     OUTPUT:
c       file "bondout"
c
c     Notes:
c     - No coordinates are written
c     - Connectivity is explicit and unambiguous
c

      integer natoms
      integer nbonds
      integer ibond(*)
      integer jbond(*)
      integer btype(*)

      integer i, iu

c     --- Open file ---
      iu = 99
      open(unit=iu, file='bondout', status='unknown')

c     --- Header ---
      write(iu,'(A)') '# bondout generated by GICForge'
      write(iu,'(A)') '# Explicit molecular connectivity'
      write(iu,'(A)') '# Atom indices are 1-based (see comments in code)'
      write(iu,'(A)') ' '

c     --- Atom and bond counts ---
      write(iu,'(A,I6)') 'NATOMS ', natoms
      write(iu,'(A,I6)') 'NBONDS ', nbonds

c     --- Bond list ---
      do 100 i = 1, nbonds

         if (btype(i) .eq. 1) then
            write(iu,'(A,2I6,A)') 'BOND ', ibond(i), jbond(i), '  1'
         else if (btype(i) .eq. 2) then
            write(iu,'(A,2I6,A)') 'BOND ', ibond(i), jbond(i), '  2'
         else if (btype(i) .eq. 3) then
            write(iu,'(A,2I6,A)') 'BOND ', ibond(i), jbond(i), '  3'
         else if (btype(i) .eq. 4) then
            write(iu,'(A,2I6,A)') 'BOND ', ibond(i), jbond(i), ' ar'
         else
            write(iu,'(A,2I6,A)') 'BOND ', ibond(i), jbond(i), '  ?'
         end if

 100  continue

c     --- Close file ---
      close(iu)

      return
      end
