"""VPT2/VCI contracts for Merlino4."""

from .contracts import (
    DavidsonSettings,
    ForceFieldSource,
    VCIRequest,
    VPT2VCIInventory,
    inventory_vpt2_vci_backends,
)
from .gaussian_qff import (
    FCHKData,
    anharmonic_input_from_gaussian_fchk,
    hessian_input_from_gaussian_fchk,
    lower_to_symmetric,
    read_gaussian_fchk_qff,
    read_indexed_qff_text,
)
from .davidson import DavidsonResult, davidson_lowest
from .harmonic import GFResult, mass_weighted_cartesian_hessian, solve_wilson_gf
from .internal_gf import (
    InternalGFResult,
    PEDTable,
    gf_from_cartesian_hessian_and_merlino_gics,
    gf_from_gaussian_fchk_with_merlino_gics,
    gf_from_hessian_input_with_merlino_gics,
    gic_labels_from_u,
    primitive_label,
)
from .models import AnharmonicInput, HessianInput
from .gui_service import (
    GFReport,
    VPT2VCIReport,
    format_gf_report,
    format_vpt2_vci_report,
    load_force_field,
    run_gf_report_from_fchk,
    run_vpt2_vci_report,
)
from .vci import (
    QuarticForceField,
    VCIBlockInfo,
    VCIOptions,
    VCIResult,
    VCIStateContribution,
    build_vci_hamiltonian,
    force_field_from_anharmonic_input,
    generate_vibrational_basis,
    solve_vci,
    solve_vci_from_anharmonic_input,
    zero_anharmonic_force_field,
)
from .vpt2 import (
    VPT2Result,
    VPT2State,
    VPT2VCIComparison,
    compare_vpt2_vci,
    compare_vpt2_vci_from_anharmonic_input,
    solve_vpt2,
    solve_vpt2_from_anharmonic_input,
)
from .workflow import VPT2VCIRun, run_python_vci_from_gaussian_fchk

__all__ = [
    "DavidsonSettings",
    "DavidsonResult",
    "AnharmonicInput",
    "FCHKData",
    "ForceFieldSource",
    "GFResult",
    "GFReport",
    "InternalGFResult",
    "HessianInput",
    "PEDTable",
    "QuarticForceField",
    "VCIBlockInfo",
    "VCIOptions",
    "VCIRequest",
    "VCIResult",
    "VCIStateContribution",
    "VPT2VCIInventory",
    "VPT2VCIRun",
    "VPT2Result",
    "VPT2State",
    "VPT2VCIComparison",
    "VPT2VCIReport",
    "anharmonic_input_from_gaussian_fchk",
    "build_vci_hamiltonian",
    "compare_vpt2_vci",
    "compare_vpt2_vci_from_anharmonic_input",
    "davidson_lowest",
    "force_field_from_anharmonic_input",
    "format_gf_report",
    "format_vpt2_vci_report",
    "generate_vibrational_basis",
    "gf_from_cartesian_hessian_and_merlino_gics",
    "gf_from_gaussian_fchk_with_merlino_gics",
    "gf_from_hessian_input_with_merlino_gics",
    "gic_labels_from_u",
    "hessian_input_from_gaussian_fchk",
    "inventory_vpt2_vci_backends",
    "load_force_field",
    "lower_to_symmetric",
    "mass_weighted_cartesian_hessian",
    "read_gaussian_fchk_qff",
    "read_indexed_qff_text",
    "primitive_label",
    "run_gf_report_from_fchk",
    "run_python_vci_from_gaussian_fchk",
    "run_vpt2_vci_report",
    "solve_vci",
    "solve_vci_from_anharmonic_input",
    "solve_vpt2",
    "solve_vpt2_from_anharmonic_input",
    "solve_wilson_gf",
    "zero_anharmonic_force_field",
]
